on: push
name: 🚀 Deploy server on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        server-dir: /home/www/argbcontrol-server/
    
    - name: 🟢 Start server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /home/www/argbcontrol-server/
          npm install
          screen -X -S argbcontrol-server kill
          screen -dmS argbcontrol-server node index.js

